// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxxvfczzduzgoacvsbnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4eHZmY3p6ZHV6Z29hY3ZzYm53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyOTI5NzMsImV4cCI6MjA1MDg2ODk3M30.EqcRyP-FAbb5pcQVEn9DNLK0kQJr3vi_dxFlpEhuksc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);